# This is for our soon to be 'hopefully' mkdocs formatted internal documentation
# Demo / Docs: https://squidfunk.github.io/mkdocs-material/

site_name: Grownetics Company Handbook
site_url: http://docs.grownetics.co/
repo_url: https://gitlab.com/grownetics/grownetics
edit_uri: edit/master/Handbook
docs_dir: Handbook
repo_url: https://gitlab.com/grownetics/grownetics
edit_uri: edit/master/Handbook
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo: 'logo.png'
nav:
- Home: 'index.md'
- How We Work: 
  - 'Introduction': 'how-we-work.md'
  - 'Onboarding': 'onboarding.md'
  - 'Team Processes': 'team-processes.md'
  - 'Working with our docs': 'documentation.md'
  - 'Meetings at Grownetics': 'meetings.md'
  - 'Legal Docs & Contracts (NDA's etc.)': 'legal.md'
- Development:
  - 'ACLs': 'Development/acls.md'
  - 'BACnet': 'Development/bacnet.md'
  - 'Best Practices': 'Development/best-practices.md'
  - 'Dev Xdebug': 'Development/dev-xdebug.md'
  - 'Dev OSX': 'Development/dev-osx.md'
  - 'Environmental Controls': 'Development/environmental-control.md'
  - 'Firmware': 'Development/firmware.md'
  - 'Getting Started': 'Development/getting-started.md'
  - 'growctl': 'Development/growctl.md'
  - 'GrowServer': 'Development/growserver.md'
  - 'How We Develop': 'Development/how-we-develop.md'
  - 'Kubernetes': 'Development/k8s.md'
  - 'Physical Server Setup Guide': 'Development/onsite-server-setup.md'
  - 'Install Grownetics': 'Development/setup.md'
  - 'Organizations': 'Development/organizations.md'
  - 'Rules Engine': 'Development/rules-engine.md'
  - 'Testing': 'Development/testing.md'
  - 'Tor Access': 'Development/tor.md'
  - 'UI/UX': 'Development/ux.md'
  - 'Writing Changelogs': 'Development/changelogs.md'
- Feature Flags:
  - 'Overview': 'FeatureFlags/overview.md'
  - 'Home Screen': 'FeatureFlags/home-screen.md'
- System:
  - 'Burnout Protection': 'System/burnout-protection.md'
  - 'Data': 'System/data.md'
- Support: 
  - 'On Call Handbook': 'on-call.md'
- Biz Dev: 
  - 'Introduction': 'sales.md'
- Project Delivery & Manufacturing: 
  - 'Project Kickoff': 'kickoff.md'
  - 'Manufacturing': 'manufacturing.md'
  - 'Ordering from MacroFab': 'macrofab.md'
  - 'Installations': 'installations.md'
  - 'Safety and Precautions': 'safety.md'
