FROM php:7.3-fpm

RUN apt-get update \
    && apt-get -y install \
    autoconf \
    curl \
    default-mysql-client \
    g++ \
    gnupg2 \
    iputils-ping \
    libicu-dev \
    libcurl4-gnutls-dev \
    libmcrypt-dev \
    libreadline-dev \
    libpng-dev \
    libxml2-dev \
    make \
    default-mysql-client \
    nodejs \
    npm \
    ruby \
    ruby-dev \
    unzip \
    vim \
    zip \
    && apt remove -y cmdtest yarn \
    && npm install -g yarn \
    && pecl install mcrypt-1.0.2 \
    && gem install -n /usr/local/bin sass \
    && yarn add bower grunt-cli \
    && echo '{ "allow_root": true }' > /root/.bowerrc \
    && docker-php-source extract \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug mcrypt \
    && docker-php-source delete \
    && docker-php-ext-install curl gd json mbstring bcmath dom intl pdo_mysql soap sockets \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /tmp/* 

ENV PHPREDIS_VERSION 3.0.0

RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

RUN echo "xdebug.mode=debug\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_port=9003\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.default_enable=1\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_connect_back=0\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.idekey=VSCODE\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=1\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY images/php/www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/html
