FROM php:7.3-fpm

RUN apt-get update \
    && apt-get -y install \
    autoconf \
    curl \
    default-mysql-client \
    g++ \
    gnupg2 \
    iputils-ping \
    libicu-dev \
    libcurl4-gnutls-dev \
    libmcrypt-dev \
    libreadline-dev \
    libpng-dev \
    libxml2-dev \
    make \
    nodejs \
    ruby \
    ruby-dev \
    unzip \
    vim \
    yarn \
    zip \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt install yarn \
    && pecl install mcrypt-1.0.2 \
    && gem install -n /usr/local/bin sass \
    && yarn add bower grunt-cli \
    && echo '{ "allow_root": true }' > /root/.bowerrc \
    && docker-php-source extract \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug mcrypt \
    && docker-php-source delete \
    && docker-php-ext-install curl gd json mbstring bcmath dom intl pdo_mysql soap sockets \
    && echo "xdebug.remote_enable=on\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_autostart=1\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_port=9000\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_handler=dbgp\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_connect_back=1\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /tmp/*

ENV PHPREDIS_VERSION 3.0.0

RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

COPY images/php/www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/html
