<?php
use Migrations\AbstractSeed;

/**
 * RuleActions seed.
 */
class RuleActionsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '1',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '2',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '2',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '3',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '3',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '4',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '4',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '5',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '5',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '6',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '6',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '7',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '7',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '8',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '8',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '9',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '9',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '10',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '10',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '11',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '11',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '12',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '12',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '13',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '13',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '14',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '14',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '15',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '15',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '16',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '16',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '17',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '17',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '18',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '18',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '19',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '19',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '20',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '20',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '21',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '21',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '22',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '22',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '23',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '23',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '24',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '24',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '25',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '25',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '26',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '26',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '27',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '27',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '28',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '28',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '29',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '29',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '30',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '30',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '31',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '31',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '32',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '32',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '33',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '33',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '34',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '34',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '35',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '35',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '36',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '36',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '37',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '37',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '38',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '38',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '39',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '39',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '40',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '40',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '41',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '41',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '42',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '42',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '43',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '43',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '44',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '44',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '45',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '45',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '46',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '46',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '47',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '47',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '48',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '48',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '49',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '49',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],

            [
                'id' => '50',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '50',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '51',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '51',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '52',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '52',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '53',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '53',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '54',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '54',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '55',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '55',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
            [
                'id' => '56',
                'created' => NULL,
                'modified' => NULL,
                'type' => '1',
                'notification_level' => '5',
                'notification_user_role' => NULL,
                'rule_id' => '56',
                'on_trigger' => '1',
                'is_default' => '1',
                'deleted' => '0000-00-00 00:00:00',
            ],
        ];

        $table = $this->table('rule_actions');
        $table->insert($data)->save();
    }
}
