<?php
use Migrations\AbstractSeed;

/**
 * RuleConditions seed.
 */
class RuleConditionsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            //CLONE
            [
                'id' => '1',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '1',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '1',
                'is_default' => '1',
            ],
            [
                'id' => '2',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '1',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '2',
                'is_default' => '1',
            ],
            [
                'id' => '3',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '1',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '3',
                'is_default' => '1',
            ],
            [
                'id' => '4',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '1',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '4',
                'is_default' => '1',
            ],
            [
                'id' => '5',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '1',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '5',
                'is_default' => '1',
            ],
            [
                'id' => '6',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '1',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '6',
                'is_default' => '1',
            ],
            [
                'id' => '7',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '1',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '7',
                'is_default' => '1',
            ],

            //VEGG
            [
                'id' => '8',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '2',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '8',
                'is_default' => '1',
            ],
            [
                'id' => '9',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '2',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '9',
                'is_default' => '1',
            ],
            [
                'id' => '10',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '2',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '10',
                'is_default' => '1',
            ],
            [
                'id' => '11',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '2',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '11',
                'is_default' => '1',
            ],
            [
                'id' => '12',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '2',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '12',
                'is_default' => '1',
            ],
            [
                'id' => '13',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '2',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '13',
                'is_default' => '1',
            ],
            [
                'id' => '14',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '2',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '14',
                'is_default' => '1',
            ],

            //BLOOM
            [
                'id' => '15',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '3',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '15',
                'is_default' => '1',
            ],
            [
                'id' => '16',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '3',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '16',
                'is_default' => '1',
            ],
            [
                'id' => '17',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '3',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '17',
                'is_default' => '1',
            ],
            [
                'id' => '18',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '3',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '18',
                'is_default' => '1',
            ],
            [
                'id' => '19',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '3',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '19',
                'is_default' => '1',
            ],
            [
                'id' => '20',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '3',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '20',
                'is_default' => '1',
            ],
            [
                'id' => '21',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '3',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '21',
                'is_default' => '1',
            ],

            //DRY
            [
                'id' => '22',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '4',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '22',
                'is_default' => '1',
            ],
            [
                'id' => '23',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '4',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '23',
                'is_default' => '1',
            ],
            [
                'id' => '24',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '4',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '24',
                'is_default' => '1',
            ],
            [
                'id' => '25',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '4',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '25',
                'is_default' => '1',
            ],
            [
                'id' => '26',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '4',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '26',
                'is_default' => '1',
            ],
            [
                'id' => '27',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '4',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '27',
                'is_default' => '1',
            ],
            [
                'id' => '28',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '4',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '28',
                'is_default' => '1',
            ],

            //CURE
            [
                'id' => '29',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '5',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '29',
                'is_default' => '1',
            ],
            [
                'id' => '30',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '5',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '30',
                'is_default' => '1',
            ],
            [
                'id' => '31',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '5',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '31',
                'is_default' => '1',
            ],
            [
                'id' => '32',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '5',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '32',
                'is_default' => '1',
            ],
            [
                'id' => '33',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '5',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '33',
                'is_default' => '1',
            ],
            [
                'id' => '34',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '5',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '34',
                'is_default' => '1',
            ],
            [
                'id' => '35',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '5',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '35',
                'is_default' => '1',
            ],

            //PROCESSING
            [
                'id' => '36',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '6',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '36',
                'is_default' => '1',
            ],
            [
                'id' => '37',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '6',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '37',
                'is_default' => '1',
            ],
            [
                'id' => '38',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '6',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '38',
                'is_default' => '1',
            ],
            [
                'id' => '39',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '6',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '39',
                'is_default' => '1',
            ],
            [
                'id' => '40',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '6',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '40',
                'is_default' => '1',
            ],
            [
                'id' => '41',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '6',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '41',
                'is_default' => '1',
            ],
            [
                'id' => '42',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '6',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '42',
                'is_default' => '1',
            ],

            //STORAGE
            [
                'id' => '43',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '7',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '43',
                'is_default' => '1',
            ],
            [
                'id' => '44',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '7',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '44',
                'is_default' => '1',
            ],
            [
                'id' => '45',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '7',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '45',
                'is_default' => '1',
            ],
            [
                'id' => '46',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '7',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '46',
                'is_default' => '1',
            ],
            [
                'id' => '47',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '7',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '47',
                'is_default' => '1',
            ],
            [
                'id' => '48',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '7',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '48',
                'is_default' => '1',
            ],
            [
                'id' => '49',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '7',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '49',
                'is_default' => '1',
            ],

            //SHIPPING
            [
                'id' => '50',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Below 20%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '8',
                'operator' => '1',
                'trigger_threshold' => '20',
                'reset_threshold' => '21',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '50',
                'is_default' => '1',
            ],
            [
                'id' => '51',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Humidity Above 90%',
                'data_source' => '5',
                'sensor_type' => '2',
                'data_id' => '8',
                'operator' => '0',
                'trigger_threshold' => '90',
                'reset_threshold' => '89',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '51',
                'is_default' => '1',
            ],
            [
                'id' => '52',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Below 13C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '8',
                'operator' => '1',
                'trigger_threshold' => '13',
                'reset_threshold' => '15',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '52',
                'is_default' => '1',
            ],
            [
                'id' => '53',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 30C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '8',
                'operator' => '0',
                'trigger_threshold' => '30',
                'reset_threshold' => '28',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '53',
                'is_default' => '1',
            ],
            [
                'id' => '54',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'Air Temperature Above 35C',
                'data_source' => '5',
                'sensor_type' => '3',
                'data_id' => '8',
                'operator' => '0',
                'trigger_threshold' => '35',
                'reset_threshold' => '33',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => 300,
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '54',
                'is_default' => '1',
            ],
            [
                'id' => '55',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Below 100ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '8',
                'operator' => '1',
                'trigger_threshold' => '100',
                'reset_threshold' => '101',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '55',
                'is_default' => '1',
            ],
            [
                'id' => '56',
                'created' => date(DATE_ATOM),
                'modified' => date(DATE_ATOM),
                'label' => 'CO2 Above 2000ppm',
                'data_source' => '5',
                'sensor_type' => '4',
                'data_id' => '8',
                'operator' => '0',
                'trigger_threshold' => '2000',
                'reset_threshold' => '1900',
                'status' => '1',
                'zone_behavior' => '1',
                'trigger_delay' => '5',
                'pending_time' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'rule_id' => '56',
                'is_default' => '1',
            ],
        ];

        $table = $this->table('rule_conditions');
        $table->insert($data)->save();
    }
}
