apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: appdb
  name: appdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appdb
    spec:
      containers:
      - args:
        - mysqld
        - --sql_mode=
        envFrom:
        - configMapRef:
            name: common-config
        # env:
        # - name: MYSQL_DATABASE
        # - name: MYSQL_PASSWORD
        # - name: MYSQL_ROOT_PASSWORD
        # - name: MYSQL_TEST_DATABASE
        # - name: MYSQL_USER
        image: mariadb:10.3
        name: appdb
        ports:
        - containerPort: 3306
        resources: {}
        # volumeMounts:
        # - mountPath: /var/lib/mysql
        #   name: appdb-claim0
      restartPolicy: Always
      # volumes:
      # - name: appdb-claim0
      #   persistentVolumeClaim:
      #     claimName: appdb-claim0
status: {}
