apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: bookstack-mysql
  name: bookstack-mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bookstack-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: bookstack
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: bookstack
        image: mysql:5.7.21
        name: bookstack-mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: bookstack-mysql-claim0
      restartPolicy: Always
      volumes:
      - name: bookstack-mysql-claim0
        persistentVolumeClaim:
          claimName: bookstack-mysql-claim0
status: {}
