apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: bookstack
  name: bookstack
spec:
  ports:
  - name: "8283"
    port: 8283
    targetPort: 80
  selector:
    io.kompose.service: bookstack
status:
  loadBalancer: {}
