apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: chronograf
  name: chronograf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chronograf
    spec:
      containers:
      - image: chronograf
        name: chronograf
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/chronograf
          name: chronograf-claim0
      restartPolicy: Always
      volumes:
      - name: chronograf-claim0
        persistentVolumeClaim:
          claimName: chronograf-claim0
status: {}
