growdash:
  environment:
    - DEV=0

phpunit:
  image: grownetics/growdash:latest
  links:
    - appdb
    - redis
    - rabbitmq
    - influxdb
    - consul
    - hub
    - chrome
#    - firefox

  environment:
    - DEV=0
    - FACILITY_NAME
    - FACILITY_ID
    - CERES
    - ENVIRONMENT
    - REMOTE_DOMAIN

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT

  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_ne: onsite=true

hub:
  image: selenium/hub
  links:
    - nginx

chrome:
  image: selenium/node-chrome
  volumes:
    - /dev/shm:/dev/shm
  links:
    - hub
    - nginx
  environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444

firefox:
 image: selenium/node-firefox
 links:
   - hub
   - nginx
 environment:
   - HUB_PORT_4444_TCP_ADDR=hub
   - HUB_PORT_4444_TCP_PORT=4444
