# The dashboard interface that humans access
growdash:
  image: grownetics/growdash:${VERSION}
  restart: always
  links:
    - appdb
    - redis
    - rabbitmq
    - influxdb
    - consul
  environment:
    - DEV
    - FACILITY_NAME
    - FACILITY_ID
    - CERES
    - DEMO
    - ENVIRONMENT
    - REMOTE_DOMAIN
    - VERSION
    - SHORT_NAME
    - SALT
    - ONSITE

    - SET_POINT_ALARM_TOLERANCE_PERCENTAGE
    - BURNOUT_PROTECTION_DELAY

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT

    - TWILIO_SID
    - TWILIO_TOKEN

    - THRESHOLD_DEVICE_BOOTS
    - THRESHOLD_DATA_RECEIVED
    - THRESHOLD_CT_ON

    - TIMEZONE_OFFSET
    - TIMEZONE

    - BACNET_URL
    - BACNET_AUTH
    - BACNET_RATE
    - BACNET_ENABLED

    - ARGUS_RATE
    - ARGUS_URL

    - SMTP_HOST
    - SMTP_USER
    - SMTP_PASS

# The API that devices talk to
deviceapi:
  image: grownetics/growdash:${VERSION}
  restart: always
  links:
    - appdb
    - redis
    - rabbitmq
    - influxdb
    - consul
  environment:
    - DEV
    - FACILITY_NAME
    - FACILITY_ID
    - CERES
    - ENVIRONMENT
    - REMOTE_DOMAIN
    - SHORT_NAME

    - BURNOUT_PROTECTION_DELAY

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT

    - THRESHOLD_DEVICE_BOOTS
    - THRESHOLD_DATA_RECEIVED
    - THRESHOLD_CT_ON

# Responsible for maintaining the socket connection to the dashboard for live data and chat
growsocket:
  image: grownetics/socketio:latest
  restart: always
  links:
    - rabbitmq
    - nginx

# Responsible for communicating with the onsite BACnet system
# Only runs if BACNET_URL is set.
growbacnet:
  image: grownetics/growdash:${VERSION}
  restart: always
  command: /var/www/html/growbacnet.sh
  links:
    - appdb
    - redis
    - influxdb
  environment:
    - DEV
    - FACILITY_NAME
    - FACILITY_ID
    - CERES
    - ENVIRONMENT
    - REMOTE_DOMAIN
    - SHORT_NAME

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT

    - BACNET_URL
    - BACNET_AUTH
    - BACNET_RATE
    - BACNET_ENABLED
    - THRESHOLD_DEVICE_BOOTS
    - THRESHOLD_DATA_RECEIVED
    - THRESHOLD_CT_ON

# 'Pulses' at a regular interval to calucate and process zone and time based rules
# Also sends notifications and monitors device health
growpulse:
  image: grownetics/growdash:${VERSION}
  restart: always
  command: /var/www/html/growpulse.sh
  links:
    - appdb
    - redis
    - rabbitmq
    - influxdb
    - consul
  environment:
    - DEV
    - FACILITY_NAME
    - FACILITY_ID
    - CERES
    - ENVIRONMENT
    - REMOTE_DOMAIN
    - SHORT_NAME
    - VERSION

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT
    - THRESHOLD_DEVICE_BOOTS
    - THRESHOLD_DATA_RECEIVED
    - THRESHOLD_CT_ON

notifications:
  image: grownetics/growdash:${VERSION}
  restart: always
  command: bash -c "chmod +x /var/www/html/notification.sh && /var/www/html/notification.sh"
  links:
    - appdb
    - redis
    - rabbitmq
    - influxdb
    - consul
  environment:
    - DEV
    - FACILITY_NAME
    - SHORT_NAME
    - FACILITY_ID
    - CERES
    - ENVIRONMENT
    - REMOTE_DOMAIN
    - VERSION

    - DB_HOSTNAME
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

    - REDIS_HOSTNAME
    - RABBIT_HOST
    - RABBIT_PORT
    - RABBIT_USER
    - RABBIT_PASS
    - INFLUX_HOST
    - INFLUX_PORT

    - TWILIO_SID
    - TWILIO_TOKEN

    - SMTP_HOST
    - SMTP_USER
    - SMTP_PASS

# Dispatches web requests
nginx:
  image: grownetics/nginx:${VERSION}
  restart: always
  links:
    - growdash
    - deviceapi

# Stores all application info, users, zones, devices, rules, notifications, etc.
appdb:
  image: mariadb
  restart: always
  command: mysqld --sql_mode=""
  environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_TEST_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD

# Caching engine for GrowDash, GrowSocket, and GrowPulse
redis:
  image: redis
  restart: always

#
# Service Discovery - Consul
#
consul:
  image: bitnami/consul
  restart: always


# Holds all data points, as well as system performance data and other time series metrics
influxdb:
  image: influxdb
  restart: always
  environment:
    - INFLUXDB_HTTP_LOG_ENABLED=false

# Alerting
kapacitor:
  image: kapacitor
  links:
    - influxdb
  environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

# Records system metrics to Influx
telegraf:
  image: telegraf
  restart: always
  links:
    - consul
    - appdb
    - influxdb
    - rabbitmq
    - redis
    - growdash
    - deviceapi
    - nginx

# Charting and display
chronograf:
  image: chronograf
  restart: always
  links:
    - influxdb
    - kapacitor

# Queues data points to be inserted into the local Influx, and out to the cloud. Served on port :15672 in development and onsite
rabbitmq:
  image: rabbitmq:3.6-management-alpine
  restart: always
  environment:
    # - RABBITMQ_DEFAULT_USER:RABBIT_USER
    - RABBITMQ_DEFAULT_USER=rabbit
    # - RABBITMQ_DEFAULT_PASS:RABBIT_PASS
    - RABBITMQ_DEFAULT_PASS=rabbit

# supercron:
#   image: grownetics/supercron:${VERSION}
#   links:
#     - consul
#     - appdb
#     - growdash
#     - redis
#     - rabbitmq
#   environment:
#     - DEV
#     - FACILITY_NAME
#     - FACILITY_ID
#     - CERES
#     - ENVIRONMENT
#     - REMOTE_DOMAIN

#     - DB_HOSTNAME
#     - MYSQL_ROOT_PASSWORD
#     - MYSQL_DATABASE
#     - MYSQL_TEST_DATABASE
#     - MYSQL_USER
#     - MYSQL_PASSWORD

#     - REDIS_HOSTNAME
#     - RABBIT_HOST
#     - RABBIT_PORT
#     - RABBIT_USER
#     - RABBIT_PASS
#     - INFLUX_HOST
#     - INFLUX_PORT
