cloud:
  image: rancher/lb-service-haproxy:v0.4.2
  ports:
    - 80:80/tcp
    - 8989:8989/tcp
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.scheduler.affinity:host_label_ne: onsite=true

growdash:
  image: grownetics/growdash:latest

deviceapi:
  image: grownetics/growdash:latest

growbacnet:
  image: grownetics/growdash:latest

growpulse:
  image: grownetics/growdash:latest

growsocket:
  image: grownetics/socketio:latest

nginx:
  image: grownetics/nginx:latest

growfaker:
  image: grownetics/growctl:latest

chronograf:
  ports:
    - 8888:8888

consul:
  ports:
    - 8500:8500