nginx:
  image: grownetics/nginx:$CI_PIPELINE_ID

growdash:
  image: grownetics/growdash:$CI_PIPELINE_ID
  environment:
      - FACILITY_NAME=${CI_PIPELINE_ID}
      - DEV=0
deviceapi:
  image: grownetics/growdash:$CI_PIPELINE_ID
growsocket:
  image: grownetics/socketio:$CI_PIPELINE_ID
growbacnet:
  image: grownetics/growdash:$CI_PIPELINE_ID
phpunit:
  image: grownetics/growdash:$CI_PIPELINE_ID
growpulse:
  image: grownetics/growdash:$CI_PIPELINE_ID
supercron:
  image: grownetics/supercron:$CI_PIPELINE_ID
notifications:
  image: grownetics/growdash:$CI_PIPELINE_ID

growfaker:
  image: grownetics/growctl:$CI_PIPELINE_ID

grafana:
  environment:
    - GF_SERVER_ROOT_URL=http://cloud.$CI_ENVIRONMENT_SLUG.development.cloudforest.io/grafana

bookstack:
  environment:
    - APP_URL=http://cloud.$CI_ENVIRONMENT_SLUG.development.cloudforest.io/wikis