apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: documentation
  name: documentation
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: documentation
    spec:
      containers:
      - image: squidfunk/mkdocs-material
        name: documentation
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /docs
          name: documentation-claim0
      restartPolicy: Always
      volumes:
      - name: documentation-claim0
        persistentVolumeClaim:
          claimName: documentation-claim0
status: {}
