apiVersion: v1
kind: Service
metadata:
  annotations:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_ne: onsite=true
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: growsocket
  name: growsocket
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: growsocket
status:
  loadBalancer: {}
