apiVersion: v1
kind: Service
metadata:
  labels:
    app: growdash
  name: growdash
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: growdash
  type: LoadBalancer
status:
  loadBalancer: {}

