apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_ne: onsite=true
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: growsocket
  name: growsocket
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: growsocket
    spec:
      containers:
      - image: grownetics/socketio:latest
        name: growsocket
        ports:
        - containerPort: 8989
        resources: {}
        volumeMounts:
        - mountPath: /srv/socket.js
          name: growsocket-claim0
      restartPolicy: Always
      volumes:
      - name: growsocket-claim0
        persistentVolumeClaim:
          claimName: growsocket-claim0
status: {}
