apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kapacitor
  name: kapacitor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kapacitor
    spec:
      containers:
      - env:
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: http://influxdb:8086
        image: kapacitor
        name: kapacitor
        resources: {}
      restartPolicy: Always
status: {}
