apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - image: telegraf
        name: telegraf
        resources: {}
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-claim0
        - mountPath: /var/run/docker.sock
          name: telegraf-claim1
      restartPolicy: Always
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
      - name: telegraf-claim1
        persistentVolumeClaim:
          claimName: telegraf-claim1
status: {}
