<?php
use Migrations\AbstractSeed;

/**
 * Devices seed.
 */
class DevicesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'label' => 'Device 1',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:03:59',
                'modified' => '2018-02-27 17:03:59',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '82',
                'version' => '',
                'api_id' => '1',
                'reboot_rate' => '1',
            ],
            [
                'id' => '2',
                'label' => 'Device 2',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:03:59',
                'modified' => '2018-02-27 17:03:59',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '88',
                'version' => '',
                'api_id' => '2',
                'reboot_rate' => '1',
            ],
            [
                'id' => '3',
                'label' => 'Device 3',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:00',
                'modified' => '2018-02-27 17:04:00',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '94',
                'version' => '',
                'api_id' => '3',
                'reboot_rate' => '1',
            ],
            [
                'id' => '4',
                'label' => 'Device 4',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:00',
                'modified' => '2018-02-27 17:04:00',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '100',
                'version' => '',
                'api_id' => '4',
                'reboot_rate' => '1',
            ],
            [
                'id' => '5',
                'label' => 'Device 5',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:00',
                'modified' => '2018-02-27 17:04:00',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '106',
                'version' => '',
                'api_id' => '5',
                'reboot_rate' => '1',
            ],
            [
                'id' => '6',
                'label' => 'Device 6',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:00',
                'modified' => '2018-02-27 17:04:00',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '112',
                'version' => '',
                'api_id' => '6',
                'reboot_rate' => '1',
            ],
            [
                'id' => '7',
                'label' => 'Device 7',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:01',
                'modified' => '2018-02-27 17:04:01',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '118',
                'version' => '',
                'api_id' => '7',
                'reboot_rate' => '1',
            ],
            [
                'id' => '8',
                'label' => 'Device 8',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:01',
                'modified' => '2018-02-27 17:04:01',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '124',
                'version' => '',
                'api_id' => '8',
                'reboot_rate' => '1',
            ],
            [
                'id' => '9',
                'label' => 'Device 9',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:01',
                'modified' => '2018-02-27 17:04:01',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '130',
                'version' => '',
                'api_id' => '9',
                'reboot_rate' => '1',
            ],
            [
                'id' => '10',
                'label' => 'Device 10',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:02',
                'modified' => '2018-02-27 17:04:02',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '136',
                'version' => '',
                'api_id' => '10',
                'reboot_rate' => '1',
            ],
            [
                'id' => '11',
                'label' => 'Device 11',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:02',
                'modified' => '2018-02-27 17:04:02',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '142',
                'version' => '',
                'api_id' => '11',
                'reboot_rate' => '1',
            ],
            [
                'id' => '12',
                'label' => 'Device 12',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:02',
                'modified' => '2018-02-27 17:04:02',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '148',
                'version' => '',
                'api_id' => '12',
                'reboot_rate' => '1',
            ],
            [
                'id' => '13',
                'label' => 'Device 13',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:03',
                'modified' => '2018-02-27 17:04:03',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '154',
                'version' => '',
                'api_id' => '13',
                'reboot_rate' => '1',
            ],
            [
                'id' => '14',
                'label' => 'Device 14',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:03',
                'modified' => '2018-02-27 17:04:03',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '160',
                'version' => '',
                'api_id' => '14',
                'reboot_rate' => '1',
            ],
            [
                'id' => '15',
                'label' => 'Device 15',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:03',
                'modified' => '2018-02-27 17:04:03',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '166',
                'version' => '',
                'api_id' => '15',
                'reboot_rate' => '1',
            ],
            [
                'id' => '16',
                'label' => 'Device 16',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:03',
                'modified' => '2018-02-27 17:04:03',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '172',
                'version' => '',
                'api_id' => '16',
                'reboot_rate' => '1',
            ],
            [
                'id' => '17',
                'label' => 'Device 17',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:04',
                'modified' => '2018-02-27 17:04:04',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '178',
                'version' => '',
                'api_id' => '17',
                'reboot_rate' => '1',
            ],
            [
                'id' => '18',
                'label' => 'Device 18',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:04',
                'modified' => '2018-02-27 17:04:04',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '184',
                'version' => '',
                'api_id' => '18',
                'reboot_rate' => '1',
            ],
            [
                'id' => '19',
                'label' => 'Device 19',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:04',
                'modified' => '2018-02-27 17:04:04',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '190',
                'version' => '',
                'api_id' => '19',
                'reboot_rate' => '1',
            ],
            [
                'id' => '20',
                'label' => 'Device 20',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:05',
                'modified' => '2018-02-27 17:04:05',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '196',
                'version' => '',
                'api_id' => '20',
                'reboot_rate' => '1',
            ],
            [
                'id' => '21',
                'label' => 'Device 21',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:05',
                'modified' => '2018-02-27 17:04:05',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '202',
                'version' => '',
                'api_id' => '21',
                'reboot_rate' => '1',
            ],
            [
                'id' => '22',
                'label' => 'Device 22',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:05',
                'modified' => '2018-02-27 17:04:05',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '208',
                'version' => '',
                'api_id' => '22',
                'reboot_rate' => '1',
            ],
            [
                'id' => '23',
                'label' => 'Device 23',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:05',
                'modified' => '2018-02-27 17:04:05',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '214',
                'version' => '',
                'api_id' => '23',
                'reboot_rate' => '1',
            ],
            [
                'id' => '24',
                'label' => 'Device 24',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:06',
                'modified' => '2018-02-27 17:04:06',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '220',
                'version' => '',
                'api_id' => '24',
                'reboot_rate' => '1',
            ],
            [
                'id' => '25',
                'label' => 'Device 25',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:06',
                'modified' => '2018-02-27 17:04:06',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '226',
                'version' => '',
                'api_id' => '25',
                'reboot_rate' => '1',
            ],
            [
                'id' => '26',
                'label' => 'Device 26',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:06',
                'modified' => '2018-02-27 17:04:06',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '232',
                'version' => '',
                'api_id' => '26',
                'reboot_rate' => '1',
            ],
            [
                'id' => '27',
                'label' => 'Device 27',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:07',
                'modified' => '2018-02-27 17:04:07',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '238',
                'version' => '',
                'api_id' => '27',
                'reboot_rate' => '1',
            ],
            [
                'id' => '28',
                'label' => 'Device 28',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:07',
                'modified' => '2018-02-27 17:04:07',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '244',
                'version' => '',
                'api_id' => '28',
                'reboot_rate' => '1',
            ],
            [
                'id' => '29',
                'label' => 'Device 29',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:07',
                'modified' => '2018-02-27 17:04:07',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '250',
                'version' => '',
                'api_id' => '29',
                'reboot_rate' => '1',
            ],
            [
                'id' => '30',
                'label' => 'Device 30',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:07',
                'modified' => '2018-02-27 17:04:07',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '256',
                'version' => '',
                'api_id' => '30',
                'reboot_rate' => '1',
            ],
            [
                'id' => '31',
                'label' => 'Device 31',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:08',
                'modified' => '2018-02-27 17:04:08',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '262',
                'version' => '',
                'api_id' => '31',
                'reboot_rate' => '1',
            ],
            [
                'id' => '32',
                'label' => 'Device 32',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:08',
                'modified' => '2018-02-27 17:04:08',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '268',
                'version' => '',
                'api_id' => '32',
                'reboot_rate' => '1',
            ],
            [
                'id' => '33',
                'label' => 'Device 33',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:08',
                'modified' => '2018-02-27 17:04:08',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '274',
                'version' => '',
                'api_id' => '33',
                'reboot_rate' => '1',
            ],
            [
                'id' => '34',
                'label' => 'Device 34',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:09',
                'modified' => '2018-02-27 17:04:09',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '280',
                'version' => '',
                'api_id' => '34',
                'reboot_rate' => '1',
            ],
            [
                'id' => '35',
                'label' => 'Device 35',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:09',
                'modified' => '2018-02-27 17:04:09',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '286',
                'version' => '',
                'api_id' => '35',
                'reboot_rate' => '1',
            ],
            [
                'id' => '36',
                'label' => 'Device 36',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:09',
                'modified' => '2018-02-27 17:04:09',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '292',
                'version' => '',
                'api_id' => '36',
                'reboot_rate' => '1',
            ],
            [
                'id' => '37',
                'label' => 'Device 37',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:10',
                'modified' => '2018-02-27 17:04:10',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '298',
                'version' => '',
                'api_id' => '37',
                'reboot_rate' => '1',
            ],
            [
                'id' => '38',
                'label' => 'Device 38',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:10',
                'modified' => '2018-02-27 17:04:10',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '304',
                'version' => '',
                'api_id' => '38',
                'reboot_rate' => '1',
            ],
            [
                'id' => '39',
                'label' => 'Device 39',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:10',
                'modified' => '2018-02-27 17:04:10',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '310',
                'version' => '',
                'api_id' => '39',
                'reboot_rate' => '1',
            ],
            [
                'id' => '40',
                'label' => 'Device 40',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:10',
                'modified' => '2018-02-27 17:04:10',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '316',
                'version' => '',
                'api_id' => '40',
                'reboot_rate' => '1',
            ],
            [
                'id' => '41',
                'label' => 'Device 41',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:11',
                'modified' => '2018-02-27 17:04:11',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '322',
                'version' => '',
                'api_id' => '41',
                'reboot_rate' => '1',
            ],
            [
                'id' => '42',
                'label' => 'Device 42',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:11',
                'modified' => '2018-02-27 17:04:11',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '328',
                'version' => '',
                'api_id' => '42',
                'reboot_rate' => '1',
            ],
            [
                'id' => '43',
                'label' => 'Device 43',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:11',
                'modified' => '2018-02-27 17:04:11',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '334',
                'version' => '',
                'api_id' => '43',
                'reboot_rate' => '1',
            ],
            [
                'id' => '44',
                'label' => 'Device 44',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:12',
                'modified' => '2018-02-27 17:04:12',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '340',
                'version' => '',
                'api_id' => '44',
                'reboot_rate' => '1',
            ],
            [
                'id' => '45',
                'label' => 'Device 45',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:12',
                'modified' => '2018-02-27 17:04:12',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '346',
                'version' => '',
                'api_id' => '45',
                'reboot_rate' => '1',
            ],
            [
                'id' => '46',
                'label' => 'Device 46',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:12',
                'modified' => '2018-02-27 17:04:12',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '352',
                'version' => '',
                'api_id' => '46',
                'reboot_rate' => '1',
            ],
            [
                'id' => '47',
                'label' => 'Device 47',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:13',
                'modified' => '2018-02-27 17:04:13',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '358',
                'version' => '',
                'api_id' => '47',
                'reboot_rate' => '1',
            ],
            [
                'id' => '48',
                'label' => 'Device 48',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:13',
                'modified' => '2018-02-27 17:04:13',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '364',
                'version' => '',
                'api_id' => '48',
                'reboot_rate' => '1',
            ],
            [
                'id' => '49',
                'label' => 'Device 49',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:13',
                'modified' => '2018-02-27 17:04:13',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '370',
                'version' => '',
                'api_id' => '49',
                'reboot_rate' => '1',
            ],
            [
                'id' => '50',
                'label' => 'Device 50',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:14',
                'modified' => '2018-02-27 17:04:14',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '376',
                'version' => '',
                'api_id' => '50',
                'reboot_rate' => '1',
            ],
            [
                'id' => '51',
                'label' => 'Device 51',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:14',
                'modified' => '2018-02-27 17:04:14',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '382',
                'version' => '',
                'api_id' => '51',
                'reboot_rate' => '1',
            ],
            [
                'id' => '52',
                'label' => 'Device 52',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:14',
                'modified' => '2018-02-27 17:04:14',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '388',
                'version' => '',
                'api_id' => '52',
                'reboot_rate' => '1',
            ],
            [
                'id' => '53',
                'label' => 'Device 53',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:15',
                'modified' => '2018-02-27 17:04:15',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '394',
                'version' => '',
                'api_id' => '53',
                'reboot_rate' => '1',
            ],
            [
                'id' => '54',
                'label' => 'Device 54',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:15',
                'modified' => '2018-02-27 17:04:15',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '400',
                'version' => '',
                'api_id' => '54',
                'reboot_rate' => '1',
            ],
            [
                'id' => '55',
                'label' => 'Device 55',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:15',
                'modified' => '2018-02-27 17:04:15',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '406',
                'version' => '',
                'api_id' => '55',
                'reboot_rate' => '1',
            ],
            [
                'id' => '56',
                'label' => 'Device 56',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:15',
                'modified' => '2018-02-27 17:04:15',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '412',
                'version' => '',
                'api_id' => '56',
                'reboot_rate' => '1',
            ],
            [
                'id' => '57',
                'label' => 'Device 57',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:16',
                'modified' => '2018-02-27 17:04:16',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '418',
                'version' => '',
                'api_id' => '57',
                'reboot_rate' => '1',
            ],
            [
                'id' => '58',
                'label' => 'Device 58',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:16',
                'modified' => '2018-02-27 17:04:16',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '424',
                'version' => '',
                'api_id' => '58',
                'reboot_rate' => '1',
            ],
            [
                'id' => '59',
                'label' => 'Device 59',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:17',
                'modified' => '2018-02-27 17:04:17',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '430',
                'version' => '',
                'api_id' => '59',
                'reboot_rate' => '1',
            ],
            [
                'id' => '60',
                'label' => 'Device 60',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:17',
                'modified' => '2018-02-27 17:04:17',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '436',
                'version' => '',
                'api_id' => '60',
                'reboot_rate' => '1',
            ],
            [
                'id' => '61',
                'label' => 'Device 61',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:17',
                'modified' => '2018-02-27 17:04:17',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '442',
                'version' => '',
                'api_id' => '61',
                'reboot_rate' => '1',
            ],
            [
                'id' => '62',
                'label' => 'Device 62',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:18',
                'modified' => '2018-02-27 17:04:18',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '448',
                'version' => '',
                'api_id' => '62',
                'reboot_rate' => '1',
            ],
            [
                'id' => '63',
                'label' => 'Device 63',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:18',
                'modified' => '2018-02-27 17:04:18',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '454',
                'version' => '',
                'api_id' => '63',
                'reboot_rate' => '1',
            ],
            [
                'id' => '64',
                'label' => 'Device 64',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:19',
                'modified' => '2018-02-27 17:04:19',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '460',
                'version' => '',
                'api_id' => '64',
                'reboot_rate' => '1',
            ],
            [
                'id' => '65',
                'label' => 'Device 65',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:20',
                'modified' => '2018-02-27 17:04:20',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '466',
                'version' => '',
                'api_id' => '65',
                'reboot_rate' => '1',
            ],
            [
                'id' => '66',
                'label' => 'Device 66',
                'mac' => '',
                'ip' => '',
                'created' => '2018-02-27 17:04:20',
                'modified' => '2018-02-27 17:04:20',
                'last_message' => NULL,
                'deleted' => '0000-00-00 00:00:00',
                'refresh_rate' => NULL,
                'map_item_id' => '472',
                'version' => '',
                'api_id' => '66',
                'reboot_rate' => '1',
            ],
        ];

        $table = $this->table('devices');
        $table->insert($data)->save();
    }
}
