<?php
use Migrations\AbstractSeed;

/**
 * SetPoints seed.
 */
class SetPointsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-Clone - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '1',
                'data_type' => '2',
                'default_setpoint_id' => '1',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-Clone - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '1',
                'data_type' => '3',
                'default_setpoint_id' => '2',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-Clone - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '1',
                'data_type' => '4',
                'default_setpoint_id' => '3',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1A - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '2',
                'data_type' => '2',
                'default_setpoint_id' => '4',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1A - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '2',
                'data_type' => '3',
                'default_setpoint_id' => '5',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1A - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '2',
                'data_type' => '4',
                'default_setpoint_id' => '6',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1B - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '3',
                'data_type' => '2',
                'default_setpoint_id' => '4',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1B - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '3',
                'data_type' => '3',
                'default_setpoint_id' => '5',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-V1B - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '3',
                'data_type' => '4',
                'default_setpoint_id' => '6',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2A - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '4',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2A - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '4',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2A - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '4',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2B - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '5',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2B - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '5',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F2B - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '5',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1B - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '6',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1B - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '6',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1B - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '6',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1A - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '7',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1A - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '7',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F1A - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '7',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3A - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '8',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3A - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '8',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3A - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '8',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3B - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '9',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3B - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '9',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F3B - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '9',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4A - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '10',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4A - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '10',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4A - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '10',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4B - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '11',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4B - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '11',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'HVAC-F4B - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '11',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Vault - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '12',
                'data_type' => '2',
                'default_setpoint_id' => '19',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Vault - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '12',
                'data_type' => '3',
                'default_setpoint_id' => '20',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Vault - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '12',
                'data_type' => '4',
                'default_setpoint_id' => '21',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Trim - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '13',
                'data_type' => '2',
                'default_setpoint_id' => '16',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Trim - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '13',
                'data_type' => '3',
                'default_setpoint_id' => '17',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Trim - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '13',
                'data_type' => '4',
                'default_setpoint_id' => '18',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Cure - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '14',
                'data_type' => '2',
                'default_setpoint_id' => '13',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Cure - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '14',
                'data_type' => '3',
                'default_setpoint_id' => '14',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Cure - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '14',
                'data_type' => '4',
                'default_setpoint_id' => '15',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 1 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '15',
                'data_type' => '2',
                'default_setpoint_id' => '10',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 1 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '15',
                'data_type' => '3',
                'default_setpoint_id' => '11',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 1 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '15',
                'data_type' => '4',
                'default_setpoint_id' => '12',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 2 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '16',
                'data_type' => '2',
                'default_setpoint_id' => '10',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 2 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '16',
                'data_type' => '3',
                'default_setpoint_id' => '11',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Dry 2 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '16',
                'data_type' => '4',
                'default_setpoint_id' => '12',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 4 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '17',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 4 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '17',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 4 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '17',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 3 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '18',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 3 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '18',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 3 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '18',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 2 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '19',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 2 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '19',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 2 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '19',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 1 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '20',
                'data_type' => '2',
                'default_setpoint_id' => '7',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:05',
                'modified' => '2018-07-20 20:44:05',
                'deleted' => NULL,
                'label' => 'Flower 1 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '20',
                'data_type' => '3',
                'default_setpoint_id' => '8',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Flower 1 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '20',
                'data_type' => '4',
                'default_setpoint_id' => '9',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Veg 1 - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '21',
                'data_type' => '2',
                'default_setpoint_id' => '4',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Veg 1 - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '21',
                'data_type' => '3',
                'default_setpoint_id' => '5',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Veg 1 - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '21',
                'data_type' => '4',
                'default_setpoint_id' => '6',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Clone Microprop - Humidity',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '22',
                'data_type' => '2',
                'default_setpoint_id' => '1',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Clone Microprop - Air Temperature',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '22',
                'data_type' => '3',
                'default_setpoint_id' => '2',
                'alert_level' => '0',
            ],
            [
                'created' => '2018-07-20 20:44:06',
                'modified' => '2018-07-20 20:44:06',
                'deleted' => NULL,
                'label' => 'Clone Microprop - Co2',
                'status' => '2',
                'value' => NULL,
                'target_type' => '0',
                'target_id' => '22',
                'data_type' => '4',
                'default_setpoint_id' => '3',
                'alert_level' => '0',
            ],
        ];

        $table = $this->table('set_points');
        $table->insert($data)->save();
    }
}
