<?php
use Migrations\AbstractSeed;

/**
 * Zones seed.
 */
class ZonesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'label' => 'HVAC-Clone',
                'created' => '2018-02-26 17:57:22',
                'modified' => '2018-02-26 17:57:22',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '1',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '1',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '2',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '4',
                'bacnet_timestamp' => '3',
            ],
            [
                'id' => '2',
                'label' => 'HVAC-V1A',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '2',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '4',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '5',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '7',
                'bacnet_timestamp' => '6',
            ],
            [
                'id' => '3',
                'label' => 'HVAC-V1B',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '3',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '7',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '8',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '10',
                'bacnet_timestamp' => '9',
            ],
            [
                'id' => '4',
                'label' => 'HVAC-F2A',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '4',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '10',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '11',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '13',
                'bacnet_timestamp' => '12',
            ],
            [
                'id' => '5',
                'label' => 'HVAC-F2B',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '5',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '13',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '14',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '16',
                'bacnet_timestamp' => '15',
            ],
            [
                'id' => '6',
                'label' => 'HVAC-F1B',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '6',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '16',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '17',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '19',
                'bacnet_timestamp' => '18',
            ],
            [
                'id' => '7',
                'label' => 'HVAC-F1A',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '7',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '19',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '20',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '22',
                'bacnet_timestamp' => '21',
            ],
            [
                'id' => '8',
                'label' => 'HVAC-F3A',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '8',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '22',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '23',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '25',
                'bacnet_timestamp' => '24',
            ],
            [
                'id' => '9',
                'label' => 'HVAC-F3B',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '9',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '25',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '26',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '28',
                'bacnet_timestamp' => '27',
            ],
            [
                'id' => '10',
                'label' => 'HVAC-F4A',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '10',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '28',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '29',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '31',
                'bacnet_timestamp' => '30',
            ],
            [
                'id' => '11',
                'label' => 'HVAC-F4B',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '11',
                'zone_type_id' => '2',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => '31',
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => '32',
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => '34',
                'bacnet_timestamp' => '33',
            ],
            [
                'id' => '12',
                'label' => 'Vault',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '12',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '7',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '13',
                'label' => 'Trim',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '13',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '6',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '14',
                'label' => 'Cure',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '14',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '5',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '15',
                'label' => 'Dry 1',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '15',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '4',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '16',
                'label' => 'Dry 2',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '16',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '4',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '17',
                'label' => 'Flower 4',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '17',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '18',
                'label' => 'Flower 3',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '18',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '19',
                'label' => 'Flower 2',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '19',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '20',
                'label' => 'Flower 1',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '20',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '21',
                'label' => 'Veg 1',
                'created' => '2018-02-26 17:57:23',
                'modified' => '2018-02-26 17:57:23',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '21',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '22',
                'label' => 'Clone Microprop',
                'created' => '2018-02-26 17:57:24',
                'modified' => '2018-02-26 17:57:24',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '22',
                'zone_type_id' => '1',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '34',
                'label' => 'Control Room',
                'created' => '2018-02-26 17:57:24',
                'modified' => '2018-02-26 17:57:24',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '34',
                'zone_type_id' => '4',
                'room_zone_id' => '0',
                'plant_zone_type_id' => '0',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '35',
                'label' => 'C-A',
                'created' => '2018-02-26 17:57:25',
                'modified' => '2018-02-26 17:57:25',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '35',
                'zone_type_id' => '3',
                'room_zone_id' => '22',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '36',
                'label' => 'C-B',
                'created' => '2018-02-26 17:57:25',
                'modified' => '2018-02-26 17:57:25',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '36',
                'zone_type_id' => '3',
                'room_zone_id' => '22',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '37',
                'label' => 'C-C',
                'created' => '2018-02-26 17:57:25',
                'modified' => '2018-02-26 17:57:25',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '37',
                'zone_type_id' => '3',
                'room_zone_id' => '22',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '38',
                'label' => 'C-D',
                'created' => '2018-02-26 17:57:25',
                'modified' => '2018-02-26 17:57:25',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '38',
                'zone_type_id' => '3',
                'room_zone_id' => '22',
                'plant_zone_type_id' => '1',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '39',
                'label' => 'V-A',
                'created' => '2018-02-26 17:57:25',
                'modified' => '2018-02-26 17:57:25',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '39',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '40',
                'label' => 'V-B',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '40',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '41',
                'label' => 'V-C',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '41',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '42',
                'label' => 'V-D',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '42',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '43',
                'label' => 'V-E',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '43',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '44',
                'label' => 'V-F',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '44',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '45',
                'label' => 'V-G',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '45',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '46',
                'label' => 'V-H',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '46',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '47',
                'label' => 'V-I',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '47',
                'zone_type_id' => '3',
                'room_zone_id' => '21',
                'plant_zone_type_id' => '2',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '48',
                'label' => 'F1-A',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '48',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '49',
                'label' => 'F1-B',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '49',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '50',
                'label' => 'F1-C',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '50',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '51',
                'label' => 'F1-D',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '51',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '52',
                'label' => 'F1-E',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '52',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '53',
                'label' => 'F1-F',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '53',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '54',
                'label' => 'F1-G',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '54',
                'zone_type_id' => '3',
                'room_zone_id' => '20',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '55',
                'label' => 'F3-A',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '55',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '56',
                'label' => 'F3-B',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '56',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '57',
                'label' => 'F3-C',
                'created' => '2018-02-26 17:57:26',
                'modified' => '2018-02-26 17:57:26',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '57',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '58',
                'label' => 'F3-D',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '58',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '59',
                'label' => 'F3-E',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '59',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '60',
                'label' => 'F3-F',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '60',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '61',
                'label' => 'F3-G',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '61',
                'zone_type_id' => '3',
                'room_zone_id' => '18',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '62',
                'label' => 'F2-A',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '62',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '63',
                'label' => 'F2-B',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '63',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '64',
                'label' => 'F2-C',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '64',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '65',
                'label' => 'F2-D',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '65',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '66',
                'label' => 'F2-E',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '66',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '67',
                'label' => 'F2-F',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '67',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '68',
                'label' => 'F2-G',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '68',
                'zone_type_id' => '3',
                'room_zone_id' => '19',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '69',
                'label' => 'F4-A',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '69',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '70',
                'label' => 'F4-B',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '70',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '71',
                'label' => 'F4-C',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '71',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '72',
                'label' => 'F4-D',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '72',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '73',
                'label' => 'F4-E',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '73',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '74',
                'label' => 'F4-F',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '74',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '75',
                'label' => 'F4-G',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '75',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '76',
                'label' => 'F4-H',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '76',
                'zone_type_id' => '3',
                'room_zone_id' => '17',
                'plant_zone_type_id' => '3',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '77',
                'label' => 'Dry 1',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '77',
                'zone_type_id' => '3',
                'room_zone_id' => '15',
                'plant_zone_type_id' => '4',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '78',
                'label' => 'Dry 2',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '78',
                'zone_type_id' => '3',
                'room_zone_id' => '16',
                'plant_zone_type_id' => '4',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '79',
                'label' => 'Trim',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '79',
                'zone_type_id' => '3',
                'room_zone_id' => '13',
                'plant_zone_type_id' => '6',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '80',
                'label' => 'Vault 1',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '80',
                'zone_type_id' => '3',
                'room_zone_id' => '14',
                'plant_zone_type_id' => '5',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
            [
                'id' => '81',
                'label' => 'Vault 2',
                'created' => '2018-02-26 17:57:27',
                'modified' => '2018-02-26 17:57:27',
                'status' => '1',
                'deleted' => '0000-00-00 00:00:00',
                'map_item_id' => '81',
                'zone_type_id' => '3',
                'room_zone_id' => '12',
                'plant_zone_type_id' => '7',
                'bacnet_hum_read' => NULL,
                'bacnet_hum_set' => NULL,
                'bacnet_temp_read' => NULL,
                'bacnet_temp_set' => NULL,
                'bacnet_co2_read' => NULL,
                'bacnet_co2_set' => NULL,
                'bacnet_timestamp' => NULL,
            ],
        ];

        $table = $this->table('zones');
        $table->insert($data)->save();
    }
}
